In [274]:
import requests
import json
import pandas as pd
#from bs4 import BeautifulSoup
import urllib.request
import numpy as np

## I used the https://footystats.org/api/ to get all the data

In [305]:
url = 'https://api.footystats.org/league-matches?key=example&league_id=2012'
#response = requests.get(api_url)
fp = urllib.request.urlopen(url)
mybytes = fp.read()
response = mybytes.decode("utf8")
fp.close()
rates = json.loads(response)

In [306]:
df_data=pd.DataFrame(rates["data"])
df_data.drop(columns=["status","revised_game_week","roundID","matches_completed_minimum","over05","over15","over25","over35","over45","over55","btts"], inplace=True)
df_data.drop(columns=["totalGoalCount","u45_potential","u35_potential","u25_potential","u15_potential","u05_potential","corners_o85_potential","corners_o95_potential","corners_o105_potential"], inplace=True)
df_data.drop(columns=["home_ppg","away_ppg","pre_match_home_ppg","pre_match_away_ppg","pre_match_teamA_overall_ppg","pre_match_teamB_overall_ppg","match_url"], inplace=True)
df_data.drop(columns=["team_a_corners","team_b_corners","totalCornerCount","offsides_potential","cards_potential","avg_potential","home_url","home_image","away_url","away_image"], inplace=True)
df_data.drop(columns=["team_a_offsides","team_b_offsides","o35_potential","o25_potential","o15_potential","o05_potential","o15HT_potential","o05HT_potential","corners_potential"],inplace=True)
df_data.drop(columns=["team_b_dangerous_attacks","team_a_attacks","team_b_attacks","team_a_xg","team_b_xg","total_xg","o45_potential","competition_id"], inplace=True)
df_data.drop(columns=["team_a_fh_cards","team_b_fh_cards","team_a_2h_cards","team_b_2h_cards","total_fh_cards","total_2h_cards","attacks_recorded","team_a_dangerous_attacks"], inplace=True)
df_data.drop(columns=["attendance","corner_timings_recorded","team_a_fh_corners","team_b_fh_corners","team_a_2h_corners","team_b_2h_corners"], inplace=True)
df_data.drop(columns=["no_home_away","btts_potential","btts_fhg_potential","btts_2hg_potential","goalTimingDisabled"],inplace=True)
df_data.drop(columns=["goals_2hg_team_a","goals_2hg_team_b","GoalCount_2hg","HTGoalCount","date_unix"], inplace=True)
df_data.drop(columns=["odds_btts_2nd_half_yes","odds_btts_2nd_half_no","ht_goals_team_a","ht_goals_team_b"], inplace=True)
df_data.drop(columns=['team_a_shotsOnTarget', 'team_b_shotsOnTarget','team_a_shotsOffTarget', 'team_b_shotsOffTarget','team_a_shots','team_b_shots','refereeID', 'coach_a_ID', 'coach_b_ID','odds_ft_1', 'odds_ft_x', 'odds_ft_2',
                      'odds_ft_over05', 'odds_ft_over15', 'odds_ft_over25', 'odds_ft_over35','odds_ft_over45', 'odds_ft_under05', 'odds_ft_under15','odds_ft_under25', 'odds_ft_under35', 'odds_ft_under45','odds_btts_yes', 'odds_btts_no', 'odds_team_a_cs_yes',
                      'odds_team_a_cs_no', 'odds_team_b_cs_yes', 'odds_team_b_cs_no','odds_doublechance_1x', 'odds_doublechance_12', 'odds_doublechance_x2','odds_1st_half_result_1', 'odds_1st_half_result_x','odds_1st_half_result_2', 'odds_2nd_half_result_1',
                      'odds_2nd_half_result_x', 'odds_2nd_half_result_2', 'odds_dnb_1','odds_dnb_2', 'odds_corners_over_75', 'odds_corners_over_85','odds_corners_over_95', 'odds_corners_over_105','odds_corners_over_115', 'odds_corners_under_75','odds_corners_under_85', 'odds_corners_under_95',
                      'odds_corners_under_105', 'odds_corners_under_115', 'odds_corners_1','odds_corners_x', 'odds_corners_2', 'odds_team_to_score_first_1','odds_team_to_score_first_x', 'odds_team_to_score_first_2','odds_win_to_nil_1', 'odds_win_to_nil_2', 'odds_1st_half_over05','odds_1st_half_over15',
                      'odds_1st_half_over25', 'odds_1st_half_over35','odds_1st_half_under05', 'odds_1st_half_under15','odds_1st_half_under25', 'odds_1st_half_under35'], inplace= True)
df_data.drop(columns=['odds_2nd_half_over05', 'odds_2nd_half_over15','odds_2nd_half_over25', 'odds_2nd_half_over35', 'odds_2nd_half_under05','odds_2nd_half_under15', 'odds_2nd_half_under25','odds_2nd_half_under35', 'odds_btts_1st_half_yes',
                      'odds_btts_1st_half_no'], inplace= True)
df_data.drop(columns=["stadium_location","homeGoals","awayGoals"],inplace=True)

In [307]:
df_data.columns

Index(['id', 'homeID', 'awayID', 'season', 'game_week', 'homeGoalCount',
       'awayGoalCount', 'team_a_yellow_cards', 'team_b_yellow_cards',
       'team_a_red_cards', 'team_b_red_cards', 'team_a_fouls', 'team_b_fouls',
       'team_a_possession', 'team_b_possession', 'stadium_name',
       'team_a_cards_num', 'team_b_cards_num', 'overallGoalCount',
       'winningTeam', 'corner_fh_count', 'corner_2h_count', 'home_name',
       'away_name'],
      dtype='object')

In [308]:
df_data.rename(columns= {"overallGoalCount":"Totalgol"}, inplace=True)
df_data.rename(columns= {"corner_fh_count":"corner_1_half"}, inplace=True)
df_data.rename(columns= {"corner_2h_count":"corner_2_half"}, inplace=True)
df_data.rename(columns= {"team_a_possession":"team_home_%possession"}, inplace=True)
df_data.rename(columns= {"team_b_possession":"team_away_%possession"}, inplace=True)
df_data.rename(columns= {"team_a_fouls":"team_home_fouls"}, inplace=True)
df_data.rename(columns= {"team_b_fouls":"team_away_fouls"}, inplace=True)
df_data.rename(columns= {"team_a_yellow_cards":"team_home_yellow_cards"}, inplace=True)
df_data.rename(columns= {"team_b_yellow_cards":"team_away_yellow_cards"}, inplace=True)
df_data.rename(columns= {"team_a_red_cards":"team_home_red_cards"}, inplace=True)
df_data.rename(columns= {"team_b_red_cards":"team_away_red_cards"}, inplace=True)

In [309]:
df_data=df_data[["game_week","home_name","homeID","away_name","awayID","winningTeam","homeGoalCount","awayGoalCount","Totalgol","team_home_%possession","team_away_%possession","team_home_fouls","team_away_fouls","team_home_yellow_cards",
                 "team_away_yellow_cards","team_home_red_cards","team_away_red_cards","corner_1_half","corner_2_half","season","id"]]

In [310]:
df_data["winningTeam"].replace(-1,"Tie",inplace=True)

In [277]:
home_name=df_data["home_name"].unique()
df_home=pd.DataFrame(home_name)

                          0
0                 Liverpool
1           West Ham United
2           AFC Bournemouth
3                   Burnley
4            Crystal Palace
5                   Watford
6         Tottenham Hotspur
7            Leicester City
8          Newcastle United
9         Manchester United
10                  Arsenal
11              Aston Villa
12   Brighton & Hove Albion
13                  Everton
14             Norwich City
15              Southampton
16          Manchester City
17         Sheffield United
18                  Chelsea
19  Wolverhampton Wanderers

In [288]:
homeid=df_data["homeID"].unique()
df_homeid=pd.DataFrame(homeid)

In [299]:
pd.concat([df_homeid,df_home], axis=1)

      0                        0
0   151                Liverpool
1   153          West Ham United
2   148          AFC Bournemouth
3   145                  Burnley
4   143           Crystal Palace
5   155                  Watford
6    92        Tottenham Hotspur
7   108           Leicester City
8   157         Newcastle United
9   149        Manchester United
10   59                  Arsenal
11  158              Aston Villa
12  209   Brighton & Hove Albion
13  144                  Everton
14  159             Norwich City
15  146              Southampton
16   93          Manchester City
17  251         Sheffield United
18  152                  Chelsea
19  223  Wolverhampton Wanderers

In [314]:
df_data

,game_week,home_name,homeID,away_name,awayID,winningTeam,homeGoalCount,awayGoalCount,Totalgol,team_home_%possession,...,team_home_fouls,team_away_fouls,team_home_yellow_cards,team_away_yellow_cards,team_home_red_cards,team_away_red_cards,corner_1_half,corner_2_half,season,id
0,1,Liverpool,151,Norwich City,159,151,4,1,5,60,...,9,9,0,2,0,0,6,7,2019/2020,578994
1,1,West Ham United,153,Manchester City,93,93,0,5,5,47,...,5,13,2,2,0,0,1,1,2019/2020,578995
2,1,AFC Bournemouth,148,Sheffield United,251,Tie,1,1,2,54,...,7,17,2,1,0,0,2,5,2019/2020,578996
3,1,Burnley,145,Southampton,146,145,3,0,3,43,...,6,11,0,0,0,0,2,7,2019/2020,578997
4,1,Crystal Palace,143,Everton,144,Tie,0,0,0,39,...,16,14,2,2,0,1,5,3,2019/2020,578998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,38,Leicester City,108,Manchester United,149,149,0,2,2,50,...,10,11,1,5,1,0,3,3,2019/2020,579369
376,38,Manchester City,93,Norwich City,159,93,5,0,5,80,...,7,4,1,1,0,0,6,3,2019/2020,579370
377,38,Newcastle United,157,Liverpool,151,151,1,3,4,33,...,10,5,1,0,0,0,3,3,2019/2020,579371
378,38,Southampton,146,Sheffield United,251,146,3,1,4,69,...,9,15,0,1,0,0,3,7,2019/2020,579372
379,38,West Ham United,153,Aston Villa,158,Tie,1,1,2,50,...,16,14,2,1,0,0,1,6,2019/2020,579373

In [316]:
#if df_data["homeGoalCount"] >df_data["awayGoalCount"]:
#    print(H)
df_data[df_data.home_name=='Liverpool']

,game_week,home_name,homeID,away_name,awayID,winningTeam,homeGoalCount,awayGoalCount,Totalgol,team_home_%possession,...,team_home_fouls,team_away_fouls,team_home_yellow_cards,team_away_yellow_cards,team_home_red_cards,team_away_red_cards,corner_1_half,corner_2_half,season,id
0,1,Liverpool,151,Norwich City,159,151,4,1,5,60,...,9,9,0,2,0,0,6,7,2019/2020,578994
26,3,Liverpool,151,Arsenal,59,151,3,1,4,55,...,7,3,1,1,0,0,6,4,2019/2020,579017
40,5,Liverpool,151,Newcastle United,157,151,3,1,4,72,...,5,4,0,0,0,0,5,6,2019/2020,724958
72,8,Liverpool,151,Leicester City,108,151,2,1,3,57,...,8,16,1,4,0,0,6,4,2019/2020,579067
98,10,Liverpool,151,Tottenham Hotspur,92,151,2,1,3,64,...,7,10,3,3,0,0,4,7,2019/2020,579087
119,12,Liverpool,151,Manchester City,93,151,3,1,4,42,...,-1,-1,0,2,0,0,7,10,2019/2020,579107
133,14,Liverpool,151,Brighton & Hove Albion,209,151,2,1,3,45,...,-1,-1,0,0,1,0,6,3,2019/2020,579127
147,15,Liverpool,151,Everton,144,151,5,2,7,51,...,-1,-1,1,2,0,0,4,7,2019/2020,579143
160,17,Liverpool,151,Watford,155,151,2,0,2,61,...,-1,-1,2,1,0,0,4,5,2019/2020,579159
197,20,Liverpool,151,Wolverhampton Wanderers,223,151,1,0,1,58,...,7,3,1,0,0,0,5,6,2019/2020,579187
208,21,Liverpool,151,Sheffield United,251,151,2,0,2,71,...,5,5,0,0,0,0,7,5,2019/2020,579197
228,23,Liverpool,151,Manchester United,149,151,2,0,2,56,...,7,10,1,3,0,0,8,8,2019/2020,579217
243,25,Liverpool,151,Southampton,146,151,4,0,4,54,...,8,14,0,2,0,0,12,5,2019/2020,579238
269,27,Liverpool,151,West Ham United,153,151,3,2,5,73,...,4,10,0,3,0,0,13,11,2019/2020,579259
278,29,Liverpool,151,AFC Bournemouth,148,151,2,1,3,68,...,10,11,0,1,0,0,7,6,2019/2020,579279
306,31,Liverpool,151,Crystal Palace,143,151,4,0,4,78,...,7,5,0,0,0,0,2,4,2019/2020,579297
327,33,Liverpool,151,Aston Villa,158,151,2,0,2,62,...,10,4,1,1,0,0,5,7,2019/2020,579317
342,35,Liverpool,151,Burnley,145,Tie,1,1,2,68,...,6,4,1,2,0,0,10,7,2019/2020,579337
369,37,Liverpool,151,Chelsea,152,151,5,3,8,49,...,8,9,1,0,0,0,2,4,2019/2020,579357